[package]
name = "blaunch"
version = "0.1.0"
authors = ["brian"]

[dependencies]

[dependencies.gtk]
version = "0.1.3"
features = ["v3_10"]

[dependencies.serde]
version = "1.0"

[dependencies.serde_derive]
version = "1.0"

[dependencies.serde_json]
version = "1.0"
